install.packages("bigrquery")
install.packages("magrittr")
install.packages("dplyr")
install.packages("reshape2")
install.packages("forecast")
install.packages("lubridate")
install.packages("zoo")